// Production static server for the built frontend (dist/).
// Used by Railway (and any other Node-based host) to serve the app.
//
// This server only serves static files — it does not implement any
// authentication or collect/store credentials. It is purely a demo
// frontend host.
import express from 'express'
import rateLimit from 'express-rate-limit'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const distDir = path.join(__dirname, 'dist')

const app = express()

// Basic rate limiting to protect against abuse of the static file routes.
const limiter = rateLimit({
  windowMs: 60 * 1000,
  limit: 300,
  standardHeaders: true,
  legacyHeaders: false,
})
app.use(limiter)

// Serve static assets (JS, CSS, images, etc.) generated by `npm run build`.
app.use(express.static(distDir))

// Serve the built index.html for the root route and any other route,
// so client-side navigation (if added later) keeps working.
app.get('*', (req, res) => {
  res.sendFile(path.join(distDir, 'index.html'))
})

// Railway (and most Node hosts) provide the port via the PORT env var.
const port = process.env.PORT || 3000

app.listen(port, '0.0.0.0', () => {
  console.log(`Server listening on 0.0.0.0:${port}`)
})
